# Sprint 2 – Data Preprocessing

## Objective

Transform the raw Microsoft MIND dataset into a recommendation-ready interaction table for downstream recommendation models.

## Outputs

- interactions.csv
- Positive interactions
- Negative interactions

## Skills Demonstrated

- Data Engineering
- Pandas
- Python
- Recommendation Systems

How do we transform raw logs into recommendation data?

# Import MINDDataLoader

# Load data

# Import BehaviorParser

# Parse impressions

# Create interaction table

# Positive interactions

# Negative interactions

# Save processed dataset

In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.data.loader import MINDDataLoader

loader = MINDDataLoader(PROJECT_ROOT / "data" / "raw" / "MINDsmall")

news, behaviors = loader.load()

print(news.shape)
print(behaviors.shape)

(51282, 8)
(156965, 5)

In [2]:
from src.data.loader import MINDDataLoader

In [3]:
import os

print(os.getcwd())

/Users/danielabalaniuc/Documents/newslens-ai/notebooks

In [4]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

In [5]:
from src.data.loader import MINDDataLoader

loader = MINDDataLoader(PROJECT_ROOT / "data" / "raw" / "MINDsmall")

news, behaviors = loader.load()

print(news.shape)
print(behaviors.shape)

(51282, 8)
(156965, 5)

In [6]:
from src.data.preprocessing import BehaviorParser

In [7]:
from src.data.preprocessing import BehaviorParser

interactions = BehaviorParser.parse_impressions(behaviors)

print(interactions.shape)

interactions.head()

(5843444, 3)

  user_id news_id  clicked
0  U13740  N55689        1
1  U13740  N35729        0
2  U91836  N20678        0
3  U91836  N39317        0
4  U91836  N58114        0

In [8]:
positive = BehaviorParser.positive_interactions(interactions)
negative = BehaviorParser.negative_interactions(interactions)

print("Positive:", positive.shape)
print("Negative:", negative.shape)

Positive: (236344, 3)
Negative: (5607100, 3)

In [9]:
from src.data.preprocessing import BehaviorParser

print(dir(BehaviorParser))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'negative_interactions', 'parse_impressions', 'positive_interactions']

In [10]:
from src.data.preprocessing import BehaviorParser

In [11]:
from src.recommenders.popularity import PopularityRecommender

model = PopularityRecommender()

model.fit(interactions)

model.recommend(10)

news_id
N55689    4316
N35729    3346
N33619    3246
N53585    2835
N63970    2578
N49685    2294
N49279    2270
N287      2128
N23446    1930
N51048    1875
Name: clicked, dtype: int64

In [12]:
top_news = (
    news.merge(
        model.recommend(10).rename("clicks"),
        left_on="news_id",
        right_index=True,
    )
)

top_news[["title", "category", "clicks"]]

                                                   title   category  clicks
32602  Three school workers charged in death of speci...       news    2128
33899  Charles Rogers, former Michigan State football...     sports    4316
39829  Prince Harry and Meghan Markle just shared a n...  lifestyle    1930
41550  College gymnast dies following training accide...       news    3246
41552                    Dean Foods files for bankruptcy    finance    2578
41883  Rep. Tim Ryan endorses Biden in Democratic pri...       news    1875
45974  Rip Taylor's Cause of Death Revealed, Memorial...         tv    2835
50365      Broadway Actress Laurel Griggs Dies at Age 13      music    2270
50688  Porsche launches into second story of New Jers...       news    3346
50714  Broadway Star Laurel Griggs Suffered Asthma At...      music    2294